### ISSUE TITLE
Undefined Variable: $curl in GlobeApi.php

### ISSUE THREAD

**Issue by rdac2012** [globelabs/api#6]
I am currently utilizing this API in cakephp 3, and when I'm in the part of getting the accesstoken, the debugger shows that variable $curl is undefined (in GlobeApi.php line 154). I think, the variable should change to $ch instead of $curl. 

Thanks!

- rejie

**Comment by adin234** [comment]
fixed.

86677bcfd1989fbdd6dfb7da0f89a967a6c6f403

**Comment by rdac2012** [comment]
thanks
