### ISSUE TITLE
newbie here :( PHP

### ISSUE THREAD

**Issue by romanferrer** [globelabs/api#8]
wala pong access_token na response yung http://developer.globelabs.com.ph/oauth/access_token
after ng post.  ito narereceive kong error sa http://developer.globelabs.com.ph/oauth/access_token
-------------------------------------------------------------
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.
-------------------------------------------------------------
sana matulungan nyo ko, salamat

**Comment by adin234** [comment]
hi, please try using https?

**Comment by romanferrer** [comment]
ito naman po yung error , 

Cannot POST /oauth/access_token

**Comment by romanferrer** [comment]
ok na master :) salamat marami :) nakakuha na ng access token :)

**Comment by romanferrer** [comment]
{
  "error": "App is not provisioned for this API Type"
}

mga sir sa error po na ito? ano po ibigsabihin?

**Comment by adin234** [comment]
You sure you enabled the specific api for your app?

**Comment by rmrhz** [comment]
First of all @romanferrer, you're not being helpful. Please provide a snippet so we can help you in debugging your problem.

**Comment by amsantos** [comment]
kindly email api@globelabsbeta.com for your concern, including your app
details to assist you further
